In [21]:
import cv2
import numpy as np
import sys
import os

# Image read & show

In [ ]:
img= cv2.imread('F:\Data Analysis\Language\python_opencv\image\pic1.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
#cv2.destroyWindows()

In [4]:
img= cv2.imread('F:\Data Analysis\Language\python_opencv\image\pic1.jpg')
cv2.imshow('image',img)
cv2.imshow('image 1',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
#cv2.destroyWindows()

## Multiple image show

In [ ]:

img1= cv2.imread('F:\Data Analysis\Language\python_opencv\image\pic3.jpg')
re_img = cv2.resize(img1,(800,700))
cv2.imshow('image3',re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
img1= cv2.imread('F:\Data Analysis\Language\python_opencv\image\pic3.jpg')
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [ ]:
img1= cv2.imread('F:\Data Analysis\Language\python_opencv\image\pic2.jpg')
re_img = cv2.resize(img1,(300,300))
h = np.hstack((re_img ,re_img,re_img))
v = np.vstack((h ,h,h))
cv2.imshow('image3',v)
#cv2.imshow('image3',h)
cv2.waitKey(0)
cv2.destroyAllWindows()

# slide Show

In [23]:
list_name = os.listdir('F:\Data Analysis\Language\python_opencv\image')
list_name

['pic1.jpg', 'pic2.jpg', 'pic3.jpg', 'pic4.jpg']

In [26]:
for i in list_name:
    path = 'F:\\Data Analysis\\Language\\python_opencv\\image'
    img_name = path + "\\" + i
    img = cv2.imread(img_name)
    img = cv2.resize(img,(300,300))
    cv2.imshow('image',img)
    cv2.waitKey(0)
cv2.destroyAllWindows()